# Generated by Django 6.1 on 2026-08-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.IntegerField(default=60, help_text='Duração em minutos'),
        ),
    ]
